CREATE TABLE Customers(
Customer_id VARCHAR PRIMARY KEY,
Customer_name VARCHAR NOT NULL
);


CREATE TABLE Locations(
Location_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Postal_code VARCHAR NULL,
City VARCHAR NOT NULL,
state VARCHAR NOT NULL,
Region VARCHAR NOT NULL,
Country VARCHAR NOT NULL

);



CREATE TABLE Products(
Product_key INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Product_id VARCHAR NOT NULL,
Category VARCHAR NOT NULL,
Sub_category VARCHAR NOT NULL,
Product_name VARCHAR NOT NULL

);


CREATE TABLE Orders(
Row_id INTEGER PRIMARY KEY,
Order_id VARCHAR NOT NULL,
Order_date DATE NOT NULL,
Ship_date DATE NOT NULL,
Ship_mode VARCHAR NOT NULL,
Customer_id VARCHAR NOT NULL REFERENCES Customers(Customer_id),
Segment VARCHAR NOT NULL,
Location_id INTEGER NOT NULL REFERENCES Locations(Location_id),
Product_id VARCHAR NOT NULL,
Sales NUMERIC NOT NULL,
Quantity INTEGER NOT NULL,
Discount NUMERIC NOT NULL,
Profit NUMERIC NOT NULL

);